

import java.awt.Color;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author miltos
 */
public class AddScoreForm extends javax.swing.JFrame {

    /**
     * Creates new form AddScoreForm
     */
    Course c=new Course();
    Student std= new Student();
    DefaultTableModel model;

    public AddScoreForm() {
        initComponents();
        c.FillCourseCombo(jComboBox_CourseId);
        std.FillStudentJTable(JTable, "");
        
        HideColumn(6);
        HideColumn(5);
        HideColumn(4);
        HideColumn(3);
        
        model=(DefaultTableModel)JTable.getModel();
         JTable.setRowHeight(40);
         JTable.setShowGrid(true);
         JTable.setGridColor(Color.blue);
         JTable.setSelectionBackground(Color.lightGray);
    }
private void HideColumn(int ColIndex){

TableColumn col=JTable.getColumnModel().getColumn(ColIndex);
        col.setMaxWidth(0);
        col.setMinWidth(0);
        col.setPreferredWidth(0);


}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel_StudentId = new javax.swing.JLabel();
        jLabel_CourseId = new javax.swing.JLabel();
        jLabel_Score = new javax.swing.JLabel();
        jTextField_StudentId = new javax.swing.JTextField();
        jTextField_Score = new javax.swing.JTextField();
        jComboBox_CourseId = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        JTable = new javax.swing.JTable();
        jButton_AddScore = new javax.swing.JButton();
        jButton_CancelScore = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Add Score");

        jLabel_StudentId.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_StudentId.setText("Student Id:");

        jLabel_CourseId.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_CourseId.setText("Course Id:");

        jLabel_Score.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_Score.setText("Score");

        JTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "first_name", "last_name", "sex", "birthdate", "phone", "address"
            }
        ));
        JTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTableMouseClicked(evt);
            }
        });
        JTable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                JTableKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(JTable);

        jButton_AddScore.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/07_plus-24.png"))); // NOI18N
        jButton_AddScore.setText("Add");
        jButton_AddScore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AddScoreActionPerformed(evt);
            }
        });

        jButton_CancelScore.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/010_x-24.png"))); // NOI18N
        jButton_CancelScore.setText("Cancel");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel_Score, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel_CourseId))
                                    .addGap(26, 26, 26)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jComboBox_CourseId, 0, 156, Short.MAX_VALUE)
                                        .addComponent(jTextField_Score)))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel_StudentId)
                                    .addGap(18, 18, 18)
                                    .addComponent(jTextField_StudentId)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton_CancelScore, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                                .addComponent(jButton_AddScore, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(261, 261, 261)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_StudentId)
                            .addComponent(jTextField_StudentId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_CourseId)
                            .addComponent(jComboBox_CourseId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_Score, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_Score, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_AddScore)
                            .addComponent(jButton_CancelScore)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTableMouseClicked
         int rowIndex=JTable.getSelectedRow();
         jTextField_StudentId.setText(JTable.getValueAt(rowIndex, 0).toString());

//
//        if(model.getValueAt(rowIndex, 1).toString().equals("Male")){
//            jRadioButton_Male.setSelected(true);
//            jRadioButton_Female.setSelected(false);
//        }else {
//            jRadioButton_Male.setSelected(false);
//            jRadioButton_Female.setSelected(true);
//        }
//        jTextField_ID.setText(model.getValueAt(rowIndex, 0).toString());
//        jTextField_FName.setText(model.getValueAt(rowIndex, 1).toString());
//        jTextField_LName.setText(model.getValueAt(rowIndex, 2).toString());
//        jTextField_Phone.setText(model.getValueAt(rowIndex, 5).toString());
//        jTextArea_Address.setText(model.getValueAt(rowIndex, 6).toString());
//
//        Date bdate;
//
//        try {
//            bdate= new SimpleDateFormat("yyyy-MM-dd").parse(model.getValueAt(rowIndex, 4).toString());
//
//            jDateChooser_Birthdate.setDate(bdate);
//        } catch (ParseException ex) {
//            Logger.getLogger(ManageStudentsForm.class.getName()).log(Level.SEVERE, null, ex);
//        }

    }//GEN-LAST:event_JTableMouseClicked

    private void JTableKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTableKeyReleased
//        if(evt.getKeyCode()==KeyEvent.VK_UP || evt.getKeyCode()==KeyEvent.VK_DOWN ){
//            rowIndex=JTable.getSelectedRow();
//            jTextField_ID.setText(model.getValueAt(rowIndex, 0).toString());
//            jTextField_FName.setText(model.getValueAt(rowIndex, 1).toString());
//            jTextField_LName.setText(model.getValueAt(rowIndex, 2).toString());
//            jTextField_Phone.setText(model.getValueAt(rowIndex, 5).toString());
//            jTextArea_Address.setText(model.getValueAt(rowIndex, 6).toString());
//
//            if(model.getValueAt(rowIndex, 1).toString().equals("Male")){
//                jRadioButton_Male.setSelected(true);
//                jRadioButton_Female.setSelected(false);
//            }else {
//                jRadioButton_Male.setSelected(false);
//                jRadioButton_Female.setSelected(true);
//            }
//            Date bdate;
//
//            try {
//                bdate= new SimpleDateFormat("yyyy-MM-dd").parse(model.getValueAt(rowIndex, 4).toString());
//
//                jDateChooser_Birthdate.setDate(bdate);
//            } catch (ParseException ex) {
//                Logger.getLogger(ManageStudentsForm.class.getName()).log(Level.SEVERE, null, ex);
//            }
//        }

    }//GEN-LAST:event_JTableKeyReleased

    private void jButton_AddScoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AddScoreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_AddScoreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddScoreForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddScoreForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddScoreForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddScoreForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddScoreForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTable JTable;
    private javax.swing.JButton jButton_AddScore;
    private javax.swing.JButton jButton_CancelScore;
    private javax.swing.JComboBox<String> jComboBox_CourseId;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_CourseId;
    private javax.swing.JLabel jLabel_Score;
    private javax.swing.JLabel jLabel_StudentId;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField_Score;
    private javax.swing.JTextField jTextField_StudentId;
    // End of variables declaration//GEN-END:variables
}
