

import java.awt.Color;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javafx.util.Duration.hours;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author miltos
 */
public class ManageCourseForm extends javax.swing.JFrame {

    

    
    Course c = new Course();
    DefaultTableModel model;
  
        

    /**
     * Creates new form ManageCourseForm
     */
    public ManageCourseForm()  {
      
        initComponents();
        c.FillCourseJTable(jTable_Courses);
        
         model=(DefaultTableModel)jTable_Courses.getModel();
         jTable_Courses.setRowHeight(40);
         jTable_Courses.setShowGrid(true);
         jTable_Courses.setGridColor(Color.yellow);
         jTable_Courses.setSelectionBackground(Color.blue);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Courses = new javax.swing.JTable();
        jLabel_Id_Courses = new javax.swing.JLabel();
        jLabel_Label_Courses = new javax.swing.JLabel();
        jLabel_Hours_Courses = new javax.swing.JLabel();
        jTextField_Id_Courses = new javax.swing.JTextField();
        jTextField_Label_Courses = new javax.swing.JTextField();
        jSpinner_Courses = new javax.swing.JSpinner();
        jButton_Add_Courses = new javax.swing.JButton();
        jButton_Cancel_Courses = new javax.swing.JButton();
        jLabel_Search_Course = new javax.swing.JLabel();
        jTextField_Search_Course = new javax.swing.JTextField();
        jButton_Edit_Courses = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 255, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Manage Courses");

        jTable_Courses.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "iid", "label", "hours_number"
            }
        ));
        jTable_Courses.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_CoursesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_Courses);

        jLabel_Id_Courses.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_Id_Courses.setText("Id");

        jLabel_Label_Courses.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_Label_Courses.setText("Label");

        jLabel_Hours_Courses.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_Hours_Courses.setText("Hours");

        jTextField_Id_Courses.setEditable(false);

        jSpinner_Courses.setModel(new javax.swing.SpinnerNumberModel(0, 0, 300, 1));

        jButton_Add_Courses.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/07_plus-24.png"))); // NOI18N
        jButton_Add_Courses.setText("Add");
        jButton_Add_Courses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Add_CoursesActionPerformed(evt);
            }
        });

        jButton_Cancel_Courses.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/010_x-24.png"))); // NOI18N
        jButton_Cancel_Courses.setText("Cancel");
        jButton_Cancel_Courses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Cancel_CoursesActionPerformed(evt);
            }
        });

        jLabel_Search_Course.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_Search_Course.setText("Search");

        jButton_Edit_Courses.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/edit-24.png"))); // NOI18N
        jButton_Edit_Courses.setText("Edit");
        jButton_Edit_Courses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Edit_CoursesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_Id_Courses, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_Hours_Courses)
                            .addComponent(jLabel_Label_Courses))
                        .addGap(66, 66, 66)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_Label_Courses)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jSpinner_Courses, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jTextField_Id_Courses)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton_Cancel_Courses, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton_Edit_Courses, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton_Add_Courses, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(184, 184, 184)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel_Search_Course)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField_Search_Course, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_Id_Courses)
                            .addComponent(jTextField_Id_Courses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_Label_Courses)
                            .addComponent(jTextField_Label_Courses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_Hours_Courses)
                            .addComponent(jSpinner_Courses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_Cancel_Courses, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_Edit_Courses, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_Add_Courses, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(62, 62, 62))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Search_Course)
                    .addComponent(jTextField_Search_Course, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 public boolean verifText(){
if(jTextField_Label_Courses.getText().equals("")|| jSpinner_Courses.getValue()==null ){
    JOptionPane.showMessageDialog(null, "One or more selections are empty,please fill all the fields");
    return false;

} 
else{
return true;
}

}
    private void jButton_Edit_CoursesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Edit_CoursesActionPerformed
	int id=Integer.valueOf(jTextField_Id_Courses.getText());	
        String label=jTextField_Label_Courses.getText();
        int hours = Integer.valueOf(jSpinner_Courses.getValue().toString());
        c.InsertUpdateDeleteCouse('u',id, label,hours);	             	
        ManageCourseForm.jTable_Courses.setModel(new DefaultTableModel(null,new Object[]{"id","label","hours"}));	
        c.FillCourseJTable(ManageCourseForm.jTable_Courses);

    }//GEN-LAST:event_jButton_Edit_CoursesActionPerformed

    private void jButton_Add_CoursesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Add_CoursesActionPerformed
AddCourseForm crs = new AddCourseForm();
                 crs.setVisible(true);
                 crs.pack();
                 crs.setLocationRelativeTo(null);
                 crs.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);




    }//GEN-LAST:event_jButton_Add_CoursesActionPerformed
int rowIndex;
    private void jTable_CoursesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_CoursesMouseClicked
        rowIndex=jTable_Courses.getSelectedRow();  
        
        jTextField_Id_Courses.setText(jTable_Courses.getValueAt(rowIndex, 0).toString());      
        
        jTextField_Label_Courses.setText(jTable_Courses.getValueAt(rowIndex, 1).toString());        
        jSpinner_Courses.setValue(Integer.valueOf(jTable_Courses.getValueAt(rowIndex, 2).toString()));
    

    }//GEN-LAST:event_jTable_CoursesMouseClicked

    private void jButton_Cancel_CoursesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Cancel_CoursesActionPerformed
     if(jTextField_Id_Courses.getText().equals("")){
        JOptionPane.showMessageDialog(null, "No Course selected");
        }
     else{
        int id=Integer.valueOf(jTextField_Id_Courses.getText());
	c.InsertUpdateDeleteCouse('d',id, null, null);
        ManageCourseForm.jTable_Courses.setModel(new DefaultTableModel(null,new Object[]{"id","label","hours"}));
	c.FillCourseJTable(ManageCourseForm.jTable_Courses);     
        MainForm.jLabel_coursescount.setText("Courses count ="+Integer.toString(MyFunction.countData("course")));
	jTextField_Id_Courses.setText("");
        jTextField_Label_Courses.setText("");
        jSpinner_Courses.setValue(0);
        
       
        }
        
        
        
        
    }//GEN-LAST:event_jButton_Cancel_CoursesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageCourseForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageCourseForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageCourseForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageCourseForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageCourseForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Add_Courses;
    private javax.swing.JButton jButton_Cancel_Courses;
    private javax.swing.JButton jButton_Edit_Courses;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_Hours_Courses;
    private javax.swing.JLabel jLabel_Id_Courses;
    private javax.swing.JLabel jLabel_Label_Courses;
    private javax.swing.JLabel jLabel_Search_Course;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner_Courses;
    public static javax.swing.JTable jTable_Courses;
    private javax.swing.JTextField jTextField_Id_Courses;
    private javax.swing.JTextField jTextField_Label_Courses;
    private javax.swing.JTextField jTextField_Search_Course;
    // End of variables declaration//GEN-END:variables
}
